### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kddiji** [vikas027/docker-gitlab-api#8]
I am testing this project. I locally setup the required environment variables `GITLAB_URL`, `GITLAB_ADMIN_USER`, and  `GITLAB_ADMIN_PASSWD`. Once I run the script I get this error below:

```
$ python3 docker-gitlab-api.py 
Traceback (most recent call last):
  File "/Users/admin/python/docker-gitlab-api.py", line 98, in <module>
    main()
  File "/Users/admin/python/docker-gitlab-api.py", line 91, in main
    name = sys.argv[1]
IndexError: list index out of range
```

Would appreciate any feedback. Great job by the day This is awesome

**Comment by vikas027** [comment]
Hey @kddiji ,

Can you tell me a bit more about your environment - like the version of GitLab, how you have installed it?

The script now is four years old :), I think the rest APIs have changed a bit which is why you are seeing this issue.

**Comment by kddiji** [comment]
sorry for the late reply. I was able to by pass that clocker and it works as a charm.  Just needed to run the script this way `/usr/local/bin/python3 personal_access_token.py testtoken 2022-08-27`.

**Comment by vikas027** [comment]
Thanks for confirming the same. I will close the issue now.
